import fs from 'node:fs'
import path from 'node:path'

const root = path.resolve(new URL('..', import.meta.url).pathname)
const source = path.join(root, 'web', 'dist')
const target = path.join(root, 'server', 'src', 'generated', 'webAssets.ts')

if (!fs.existsSync(path.join(source, 'index.html'))) {
  throw new Error('web/dist/index.html is missing; build the Web frontend first')
}

const files = {}
function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) walk(full)
    else files['/' + path.relative(source, full).split(path.sep).join('/')] = fs.readFileSync(full).toString('base64')
  }
}
walk(source)
fs.mkdirSync(path.dirname(target), { recursive: true })
fs.writeFileSync(target, `// Generated by scripts/embed-web.mjs. Do not edit.\nexport const webAssets: Record<string, string> = ${JSON.stringify(files)}\n`)
