import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const target = path.join(root, 'protocol', 'src', 'generated', 'version.ts')

function normalizeVersion(raw) {
  const trimmed = String(raw ?? '').trim()
  if (!trimmed) return null
  return trimmed.startsWith('v') || trimmed.startsWith('V') ? trimmed.slice(1) : trimmed
}

function normalizeCommit(raw) {
  const trimmed = String(raw ?? '').trim()
  if (!trimmed) return null
  return trimmed.slice(0, 7)
}

function readTagVersion() {
  const fromEnv = normalizeVersion(process.env.SHELLINK_VERSION)
  if (fromEnv) return fromEnv

  if (process.env.GITHUB_REF_TYPE === 'tag') {
    const fromRef = normalizeVersion(process.env.GITHUB_REF_NAME)
    if (fromRef) return fromRef
  }

  try {
    const tag = execFileSync('git', ['describe', '--tags', '--exact-match', 'HEAD'], {
      cwd: root,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
    return normalizeVersion(tag)
  } catch {
    return null
  }
}

function readPackageVersion() {
  const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
  const version = normalizeVersion(pkg.version)
  if (!version) throw new Error('package.json is missing a usable version field')
  return version
}

function readGitCommit() {
  const fromEnv = normalizeCommit(process.env.SHELLINK_GIT_COMMIT)
  if (fromEnv) return { commit: fromEnv, source: 'env' }

  try {
    const hash = execFileSync('git', ['rev-parse', '--short=7', 'HEAD'], {
      cwd: root,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
    const commit = normalizeCommit(hash)
    if (commit) return { commit, source: 'git' }
  } catch {
    // fall through
  }

  return { commit: 'unknown', source: 'fallback' }
}

const fromTag = readTagVersion()
const version = fromTag ?? readPackageVersion()
const versionSource = fromTag ? 'tag' : 'package.json'
const { commit, source: commitSource } = readGitCommit()

fs.mkdirSync(path.dirname(target), { recursive: true })
fs.writeFileSync(
  target,
  [
    '// Generated by scripts/inject-version.mjs. Do not edit.',
    `export const VERSION = ${JSON.stringify(version)}`,
    `export const GIT_COMMIT = ${JSON.stringify(commit)}`,
    '',
  ].join('\n'),
)
console.log(`Injected version ${version} (from ${versionSource}), commit ${commit} (from ${commitSource})`)
